### ISSUE TITLE
Add support for saving emoji-only mode chats

### ISSUE THREAD

**Issue by benjaminrsherman** [elihschiff/Rubber-Duck#2]
The state of emoji-only mode chats currently reset when the bot restarts.  This means that chats which should stay emoji-only must be hard coded into `server.js`.  A better solution would be to keep a json file to store the current list of chats in emoji-only mode, updating on state change, and loading an array from this file on boot.

**Comment by elihschiff** [comment]
I can add this. I want to learn database design over the summer or some other way of saving data so we don't end up with tons of storage files
