### ISSUE TITLE
Why are there no Bonobos.

### ISSUE THREAD

**Issue by chrisj1** [elihschiff/Rubber-Duck#9]
![image](https://user-images.githubusercontent.com/12666959/55990498-cc4c6b00-5c75-11e9-9791-b1c93ac3fe49.png)

**Comment by benjaminrsherman** [comment]
Where would you place said bonobos?

**Comment by chrisj1** [comment]
We need a series of Bonobo related commands.

**Comment by benjaminrsherman** [comment]
Please feel free to suggest commands or send pull requests with support for those commands.  Remember that this is Rubber Duck, not Rubber Bonobo.

**Comment by chrisj1** [comment]
Just made pull request
